on:
  pull_request:
  push:
    branches:
      - main
      - try/**
    tags-ignore:
      - v*.*.*

name: Checks & Tests

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - windows
          - macos
        version:
          - stable
          - 1.64.0

    name: Test on ${{ matrix.platform }} with ${{ matrix.version }}
    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ matrix.version }}"
          override: true
      - name: Add clippy
        run: rustup component add clippy
      - name: Test (stable, latest deps)
        if: matrix.version == 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Test (msrv, locked deps)
        if: matrix.version != 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--locked"

  clippy:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-freebsd
            platform: ubuntu-latest
          - target: x86_64-unknown-netbsd
            platform: ubuntu-latest
            experimental: true
          #- target: x86_64-unknown-redox
          #  platform: ubuntu-latest
          #  experimental: true
          - target: x86_64-unknown-linux-gnu
            platform: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            platform: ubuntu-latest
          - target: x86_64-apple-darwin
            platform: macos-latest
          - target: x86_64-pc-windows-msvc
            platform: windows-latest
          - target: armv7-unknown-linux-gnueabihf
            platform: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            platform: ubuntu-latest
            experimental: true
          - target: aarch64-unknown-linux-gnu
            platform: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            platform: ubuntu-latest
            experimental: true
          - target: aarch64-apple-darwin
            platform: macos-latest
          - target: aarch64-pc-windows-msvc
            platform: windows-latest
          - target: riscv64gc-unknown-linux-gnu
            platform: ubuntu-latest
            experimental: true

    name: Check on ${{ matrix.target }}
    runs-on: ${{ matrix.platform }}
    continue-on-error: "${{ !!matrix.experimental }}"

    steps:
      - uses: actions/checkout@v2

      - name: Add cross platform tools
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install -y \
            musl musl-dev musl-tools \
            gcc-aarch64-linux-gnu \
            gcc-riscv64-linux-gnu \
            gcc-arm-linux-gnueabihf

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }}

  # Dummy job to have a stable name for the "all tests pass" requirement
  tests-pass:
    name: Tests pass
    needs:
    - test
    - clippy
    runs-on: ubuntu-latest
    steps:
    - run: echo "Tests pass"
